### ISSUE TITLE
Create payment without specify any method

### ISSUE THREAD

**Issue by link911** [sourcefabric/payum-mollie#1]
Hello,

It will be useful to create a payment without specify method it at Symfony level but use configuration defined in Mollie console.

Why do not let Mollie to decide what payment method the client want to use?
In case?
The payment method "creditcard" in your bundle could be replaced to a generic empty method.
The customer will be forward to Mollie checkout page and he could choice credit card method (if enabled) or any enabled payment method.

The only thing to do is remove the 'method' parameter in `PayHelper\Payum\Mollie\Action\Api\CreateCaptureAction` file and a very light refacto of `PayHelper\Payum\Mollie\Action`  at the end of execute() method.

These modifications should help to implement a generic implementation of Mollie.

Thanks for your work :)

Regards

**Comment by takeit** [comment]
Hi @link911,

feel free to create a Pull Request! 👍

**Comment by link911** [comment]
It's done.
Must i do another thing to validate merge request? (first merge request ever ^^)

**Comment by takeit** [comment]
Resolved by #2
